// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/distribution/distribution.proto

package pharmacy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Distributor struct {
	Id                    string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity              int64    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxLoad               int64    `protobuf:"varint,3,opt,name=max_load,json=maxLoad,proto3" json:"max_load,omitempty"`
	CarMake               string   `protobuf:"bytes,4,opt,name=car_make,json=carMake,proto3" json:"car_make,omitempty"`
	CarModel              string   `protobuf:"bytes,5,opt,name=car_model,json=carModel,proto3" json:"car_model,omitempty"`
	Name                  string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	CarrierId             string   `protobuf:"bytes,7,opt,name=carrier_id,json=carrierId,proto3" json:"carrier_id,omitempty"`
	AvailableForTransport bool     `protobuf:"varint,8,opt,name=available_for_transport,json=availableForTransport,proto3" json:"available_for_transport,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Distributor) Reset()         { *m = Distributor{} }
func (m *Distributor) String() string { return proto.CompactTextString(m) }
func (*Distributor) ProtoMessage()    {}
func (*Distributor) Descriptor() ([]byte, []int) {
	return fileDescriptor_30345d94043a7c11, []int{0}
}

func (m *Distributor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Distributor.Unmarshal(m, b)
}
func (m *Distributor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Distributor.Marshal(b, m, deterministic)
}
func (m *Distributor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Distributor.Merge(m, src)
}
func (m *Distributor) XXX_Size() int {
	return xxx_messageInfo_Distributor.Size(m)
}
func (m *Distributor) XXX_DiscardUnknown() {
	xxx_messageInfo_Distributor.DiscardUnknown(m)
}

var xxx_messageInfo_Distributor proto.InternalMessageInfo

func (m *Distributor) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Distributor) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Distributor) GetMaxLoad() int64 {
	if m != nil {
		return m.MaxLoad
	}
	return 0
}

func (m *Distributor) GetCarMake() string {
	if m != nil {
		return m.CarMake
	}
	return ""
}

func (m *Distributor) GetCarModel() string {
	if m != nil {
		return m.CarModel
	}
	return ""
}

func (m *Distributor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Distributor) GetCarrierId() string {
	if m != nil {
		return m.CarrierId
	}
	return ""
}

func (m *Distributor) GetAvailableForTransport() bool {
	if m != nil {
		return m.AvailableForTransport
	}
	return false
}

type Requirements struct {
	Capacity             int64    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxLoad              int64    `protobuf:"varint,2,opt,name=max_load,json=maxLoad,proto3" json:"max_load,omitempty"`
	CarMake              string   `protobuf:"bytes,3,opt,name=car_make,json=carMake,proto3" json:"car_make,omitempty"`
	CarModel             string   `protobuf:"bytes,4,opt,name=car_model,json=carModel,proto3" json:"car_model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Requirements) Reset()         { *m = Requirements{} }
func (m *Requirements) String() string { return proto.CompactTextString(m) }
func (*Requirements) ProtoMessage()    {}
func (*Requirements) Descriptor() ([]byte, []int) {
	return fileDescriptor_30345d94043a7c11, []int{1}
}

func (m *Requirements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requirements.Unmarshal(m, b)
}
func (m *Requirements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requirements.Marshal(b, m, deterministic)
}
func (m *Requirements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requirements.Merge(m, src)
}
func (m *Requirements) XXX_Size() int {
	return xxx_messageInfo_Requirements.Size(m)
}
func (m *Requirements) XXX_DiscardUnknown() {
	xxx_messageInfo_Requirements.DiscardUnknown(m)
}

var xxx_messageInfo_Requirements proto.InternalMessageInfo

func (m *Requirements) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Requirements) GetMaxLoad() int64 {
	if m != nil {
		return m.MaxLoad
	}
	return 0
}

func (m *Requirements) GetCarMake() string {
	if m != nil {
		return m.CarMake
	}
	return ""
}

func (m *Requirements) GetCarModel() string {
	if m != nil {
		return m.CarModel
	}
	return ""
}

type Response struct {
	Distributor          *Distributor   `protobuf:"bytes,1,opt,name=distributor,proto3" json:"distributor,omitempty"`
	Distributors         []*Distributor `protobuf:"bytes,2,rep,name=distributors,proto3" json:"distributors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_30345d94043a7c11, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetDistributor() *Distributor {
	if m != nil {
		return m.Distributor
	}
	return nil
}

func (m *Response) GetDistributors() []*Distributor {
	if m != nil {
		return m.Distributors
	}
	return nil
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30345d94043a7c11, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Distributor)(nil), "pharmacy.Distributor")
	proto.RegisterType((*Requirements)(nil), "pharmacy.Requirements")
	proto.RegisterType((*Response)(nil), "pharmacy.Response")
	proto.RegisterType((*GetRequest)(nil), "pharmacy.GetRequest")
}

func init() {
	proto.RegisterFile("proto/distribution/distribution.proto", fileDescriptor_30345d94043a7c11)
}

var fileDescriptor_30345d94043a7c11 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4f, 0xea, 0x40,
	0x14, 0x85, 0x5f, 0x5b, 0x1e, 0x94, 0x0b, 0x79, 0x8b, 0x79, 0xa2, 0x23, 0xc6, 0xa4, 0x69, 0x62,
	0xc2, 0x0a, 0x13, 0x4c, 0x34, 0x2e, 0x8d, 0x04, 0x63, 0x22, 0x9b, 0xea, 0xce, 0x45, 0x73, 0xe9,
	0x8c, 0x71, 0x42, 0xdb, 0xa9, 0xd3, 0x81, 0xc0, 0x42, 0xff, 0xb6, 0x5b, 0xd3, 0xc1, 0x42, 0xbb,
	0x80, 0x5d, 0xcf, 0xfd, 0x4e, 0x67, 0x72, 0xce, 0x1d, 0xb8, 0xc8, 0x94, 0xd4, 0xf2, 0x92, 0x89,
	0x5c, 0x2b, 0x31, 0x5b, 0x68, 0x21, 0xd3, 0x9a, 0x18, 0x1a, 0x4e, 0xdc, 0xec, 0x1d, 0x55, 0x82,
	0xd1, 0xda, 0xff, 0xb6, 0xa0, 0x33, 0x2e, 0x0d, 0x52, 0x91, 0x7f, 0x60, 0x0b, 0x46, 0x2d, 0xcf,
	0x1a, 0xb4, 0x03, 0x5b, 0x30, 0xd2, 0x07, 0x37, 0xc2, 0x0c, 0x23, 0xa1, 0xd7, 0xd4, 0xf6, 0xac,
	0x81, 0x13, 0x6c, 0x35, 0x39, 0x05, 0x37, 0xc1, 0x55, 0x18, 0x4b, 0x64, 0xd4, 0x31, 0xac, 0x95,
	0xe0, 0xea, 0x49, 0x22, 0x2b, 0x50, 0x84, 0x2a, 0x4c, 0x70, 0xce, 0x69, 0xc3, 0x1c, 0xd6, 0x8a,
	0x50, 0x4d, 0x71, 0xce, 0xc9, 0x19, 0xb4, 0x0d, 0x92, 0x8c, 0xc7, 0xf4, 0xaf, 0x61, 0x85, 0x77,
	0x5a, 0x68, 0x42, 0xa0, 0x91, 0x62, 0xc2, 0x69, 0xd3, 0xcc, 0xcd, 0x37, 0x39, 0x07, 0x88, 0x50,
	0x29, 0xc1, 0x55, 0x28, 0x18, 0x6d, 0x19, 0xd2, 0xfe, 0x9d, 0x3c, 0x32, 0x72, 0x0d, 0x27, 0xb8,
	0x44, 0x11, 0xe3, 0x2c, 0xe6, 0xe1, 0x9b, 0x54, 0xa1, 0x56, 0x98, 0xe6, 0x99, 0x54, 0x9a, 0xba,
	0x9e, 0x35, 0x70, 0x83, 0xde, 0x16, 0x4f, 0xa4, 0x7a, 0x29, 0xa1, 0xff, 0x09, 0xdd, 0x80, 0x7f,
	0x2c, 0x84, 0xe2, 0x09, 0x4f, 0x75, 0x5e, 0x4b, 0x6a, 0x1d, 0x48, 0x6a, 0xef, 0x4f, 0xea, 0x1c,
	0x48, 0xda, 0xa8, 0x27, 0xf5, 0xbf, 0xc0, 0x0d, 0x78, 0x9e, 0xc9, 0x34, 0xe7, 0xe4, 0x06, 0x3a,
	0x6c, 0xb7, 0x03, 0x73, 0x7b, 0x67, 0xd4, 0x1b, 0x96, 0x4b, 0x1a, 0x56, 0x16, 0x14, 0x54, 0x9d,
	0xe4, 0x16, 0xba, 0x15, 0x99, 0x53, 0xdb, 0x73, 0xf6, 0xff, 0x59, 0xb3, 0xfa, 0x5d, 0x80, 0x07,
	0xae, 0x8b, 0x06, 0x78, 0xae, 0x47, 0xaf, 0xf0, 0x7f, 0x5c, 0x79, 0x26, 0xcf, 0x5c, 0x2d, 0x45,
	0xc4, 0xc9, 0x18, 0x8e, 0x26, 0x22, 0x65, 0x77, 0x65, 0x81, 0xf7, 0x9b, 0xd6, 0xc9, 0xf1, 0xee,
	0x86, 0x6a, 0x87, 0x7d, 0x52, 0x9d, 0x6f, 0xc2, 0xf9, 0x7f, 0x66, 0x4d, 0xf3, 0xe8, 0xae, 0x7e,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x1c, 0xa3, 0x39, 0x9d, 0x02, 0x00, 0x00,
}
