// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/distribution/distribution.proto

package pharmacy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DistributionService service

type DistributionService interface {
	FindAvailableCarrier(ctx context.Context, in *Requirements, opts ...client.CallOption) (*Response, error)
}

type distributionService struct {
	c    client.Client
	name string
}

func NewDistributionService(name string, c client.Client) DistributionService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pharmacy"
	}
	return &distributionService{
		c:    c,
		name: name,
	}
}

func (c *distributionService) FindAvailableCarrier(ctx context.Context, in *Requirements, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DistributionService.FindAvailableCarrier", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DistributionService service

type DistributionServiceHandler interface {
	FindAvailableCarrier(context.Context, *Requirements, *Response) error
}

func RegisterDistributionServiceHandler(s server.Server, hdlr DistributionServiceHandler, opts ...server.HandlerOption) error {
	type distributionService interface {
		FindAvailableCarrier(ctx context.Context, in *Requirements, out *Response) error
	}
	type DistributionService struct {
		distributionService
	}
	h := &distributionServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DistributionService{h}, opts...))
}

type distributionServiceHandler struct {
	DistributionServiceHandler
}

func (h *distributionServiceHandler) FindAvailableCarrier(ctx context.Context, in *Requirements, out *Response) error {
	return h.DistributionServiceHandler.FindAvailableCarrier(ctx, in, out)
}
