// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/prescription/pharmacy.proto

package pharmacy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Prescription struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string      `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Quantity             int32       `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Pharmacies           []*Pharmacy `protobuf:"bytes,4,rep,name=pharmacies,proto3" json:"pharmacies,omitempty"`
	CarrierTransportId   string      `protobuf:"bytes,5,opt,name=carrier_transport_id,json=carrierTransportId,proto3" json:"carrier_transport_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Prescription) Reset()         { *m = Prescription{} }
func (m *Prescription) String() string { return proto.CompactTextString(m) }
func (*Prescription) ProtoMessage()    {}
func (*Prescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e555570155fa11b, []int{0}
}

func (m *Prescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prescription.Unmarshal(m, b)
}
func (m *Prescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prescription.Marshal(b, m, deterministic)
}
func (m *Prescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prescription.Merge(m, src)
}
func (m *Prescription) XXX_Size() int {
	return xxx_messageInfo_Prescription.Size(m)
}
func (m *Prescription) XXX_DiscardUnknown() {
	xxx_messageInfo_Prescription.DiscardUnknown(m)
}

var xxx_messageInfo_Prescription proto.InternalMessageInfo

func (m *Prescription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Prescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Prescription) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Prescription) GetPharmacies() []*Pharmacy {
	if m != nil {
		return m.Pharmacies
	}
	return nil
}

func (m *Prescription) GetCarrierTransportId() string {
	if m != nil {
		return m.CarrierTransportId
	}
	return ""
}

type Pharmacy struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PharmacistId         string   `protobuf:"bytes,2,opt,name=pharmacist_id,json=pharmacistId,proto3" json:"pharmacist_id,omitempty"`
	PharmacyLocation     string   `protobuf:"bytes,3,opt,name=pharmacy_location,json=pharmacyLocation,proto3" json:"pharmacy_location,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pharmacy) Reset()         { *m = Pharmacy{} }
func (m *Pharmacy) String() string { return proto.CompactTextString(m) }
func (*Pharmacy) ProtoMessage()    {}
func (*Pharmacy) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e555570155fa11b, []int{1}
}

func (m *Pharmacy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pharmacy.Unmarshal(m, b)
}
func (m *Pharmacy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pharmacy.Marshal(b, m, deterministic)
}
func (m *Pharmacy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pharmacy.Merge(m, src)
}
func (m *Pharmacy) XXX_Size() int {
	return xxx_messageInfo_Pharmacy.Size(m)
}
func (m *Pharmacy) XXX_DiscardUnknown() {
	xxx_messageInfo_Pharmacy.DiscardUnknown(m)
}

var xxx_messageInfo_Pharmacy proto.InternalMessageInfo

func (m *Pharmacy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pharmacy) GetPharmacistId() string {
	if m != nil {
		return m.PharmacistId
	}
	return ""
}

func (m *Pharmacy) GetPharmacyLocation() string {
	if m != nil {
		return m.PharmacyLocation
	}
	return ""
}

func (m *Pharmacy) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	DrugCreated          bool          `protobuf:"varint,1,opt,name=Drug_created,json=DrugCreated,proto3" json:"Drug_created,omitempty"`
	Prescription         *Prescription `protobuf:"bytes,2,opt,name=prescription,proto3" json:"prescription,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e555570155fa11b, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetDrugCreated() bool {
	if m != nil {
		return m.DrugCreated
	}
	return false
}

func (m *Response) GetPrescription() *Prescription {
	if m != nil {
		return m.Prescription
	}
	return nil
}

type GetResponse struct {
	Prescriptions        []*Prescription `protobuf:"bytes,1,rep,name=prescriptions,proto3" json:"prescriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e555570155fa11b, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetPrescriptions() []*Prescription {
	if m != nil {
		return m.Prescriptions
	}
	return nil
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e555570155fa11b, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Prescription)(nil), "pharmacy.Prescription")
	proto.RegisterType((*Pharmacy)(nil), "pharmacy.Pharmacy")
	proto.RegisterType((*Response)(nil), "pharmacy.Response")
	proto.RegisterType((*GetResponse)(nil), "pharmacy.GetResponse")
	proto.RegisterType((*GetRequest)(nil), "pharmacy.GetRequest")
}

func init() { proto.RegisterFile("proto/prescription/pharmacy.proto", fileDescriptor_7e555570155fa11b) }

var fileDescriptor_7e555570155fa11b = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcd, 0x4e, 0xe3, 0x30,
	0x18, 0xdc, 0xf4, 0x6f, 0xb3, 0x5f, 0xd2, 0x55, 0xf7, 0xdb, 0x02, 0x51, 0x4f, 0x69, 0xb8, 0x54,
	0x42, 0x6a, 0x51, 0xb8, 0x21, 0x2e, 0xfc, 0x48, 0x55, 0x05, 0x87, 0x2a, 0x70, 0x8f, 0x42, 0x6c,
	0x81, 0x25, 0x48, 0x52, 0xdb, 0x41, 0xea, 0x03, 0xf0, 0x16, 0x3c, 0x0d, 0x4f, 0x86, 0xea, 0xc4,
	0x8d, 0x0b, 0xea, 0xcd, 0xdf, 0xcc, 0x68, 0x66, 0x3e, 0xdb, 0x30, 0x2e, 0x78, 0x2e, 0xf3, 0x59,
	0xc1, 0xa9, 0x48, 0x39, 0x2b, 0x24, 0xcb, 0xb3, 0x59, 0xf1, 0x9c, 0xf0, 0xd7, 0x24, 0x5d, 0x4f,
	0x15, 0x87, 0xb6, 0x9e, 0x83, 0x4f, 0x0b, 0xdc, 0xa5, 0xa1, 0xc4, 0xbf, 0xd0, 0x62, 0xc4, 0xb3,
	0x7c, 0x6b, 0xf2, 0x27, 0x6a, 0x31, 0x82, 0x3e, 0x38, 0xa4, 0xa1, 0xbd, 0x96, 0x22, 0x4c, 0x08,
	0x47, 0x60, 0xaf, 0xca, 0x24, 0x93, 0x4c, 0xae, 0xbd, 0xb6, 0x6f, 0x4d, 0xba, 0xd1, 0x76, 0xc6,
	0x10, 0xa0, 0x8e, 0x62, 0x54, 0x78, 0x1d, 0xbf, 0x3d, 0x71, 0x42, 0x9c, 0x6e, 0xdb, 0x2c, 0xeb,
	0x43, 0x64, 0xa8, 0xf0, 0x14, 0x86, 0x69, 0xc2, 0x39, 0xa3, 0x3c, 0x96, 0x3c, 0xc9, 0x44, 0x91,
	0x73, 0x19, 0x33, 0xe2, 0x75, 0x55, 0x34, 0xd6, 0xdc, 0x83, 0xa6, 0x16, 0x24, 0x78, 0xb7, 0xc0,
	0xd6, 0x56, 0x3f, 0x16, 0x38, 0x86, 0xbe, 0x36, 0x17, 0xca, 0xa7, 0x5a, 0xc1, 0x6d, 0xc0, 0x05,
	0xc1, 0x13, 0xf8, 0xa7, 0x4b, 0xc5, 0x2f, 0x79, 0x9a, 0xa8, 0x5d, 0xdb, 0x4a, 0x38, 0xd0, 0xc4,
	0x5d, 0x8d, 0xe3, 0x11, 0xfc, 0x2e, 0x05, 0xe5, 0x1b, 0xaf, 0x8e, 0x92, 0xf4, 0x36, 0xe3, 0x82,
	0x04, 0x0c, 0xec, 0x88, 0x8a, 0x22, 0xcf, 0x04, 0xc5, 0x31, 0xb8, 0x37, 0xbc, 0x7c, 0x8a, 0x53,
	0x4e, 0x13, 0x49, 0xab, 0x42, 0x76, 0xe4, 0x6c, 0xb0, 0xeb, 0x0a, 0xc2, 0x73, 0x70, 0xcd, 0x47,
	0x52, 0xc5, 0x9c, 0xf0, 0xd0, 0xb8, 0x1e, 0x83, 0x8d, 0x76, 0xb4, 0xc1, 0x2d, 0x38, 0x73, 0x2a,
	0xb7, 0x69, 0x17, 0xd0, 0x37, 0x69, 0xe1, 0x59, 0xea, 0xaa, 0xf7, 0x79, 0xed, 0x8a, 0x03, 0x17,
	0x40, 0x99, 0xad, 0x4a, 0x2a, 0x64, 0xf8, 0x61, 0xc1, 0x7f, 0x53, 0x7d, 0x4f, 0xf9, 0x1b, 0x4b,
	0x29, 0x5e, 0x01, 0x56, 0xcd, 0x77, 0xfe, 0xcb, 0x9e, 0x88, 0x91, 0xf1, 0xca, 0xba, 0x65, 0xf0,
	0x0b, 0x2f, 0x61, 0x30, 0xa7, 0xd2, 0x14, 0x0a, 0x1c, 0x36, 0xca, 0xa6, 0xc5, 0xe8, 0xe0, 0x1b,
	0xaa, 0x2d, 0x1e, 0x7b, 0xea, 0x0b, 0x9f, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xb2, 0x04,
	0x87, 0xe7, 0x02, 0x00, 0x00,
}
