// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/prescription/pharmacy.proto

package pharmacy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PrescriptionService service

type PrescriptionService interface {
	CreatePrescription(ctx context.Context, in *Prescription, opts ...client.CallOption) (*Response, error)
	GetPrescriptions(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
}

type prescriptionService struct {
	c    client.Client
	name string
}

func NewPrescriptionService(name string, c client.Client) PrescriptionService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pharmacy"
	}
	return &prescriptionService{
		c:    c,
		name: name,
	}
}

func (c *prescriptionService) CreatePrescription(ctx context.Context, in *Prescription, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PrescriptionService.CreatePrescription", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prescriptionService) GetPrescriptions(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.name, "PrescriptionService.GetPrescriptions", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PrescriptionService service

type PrescriptionServiceHandler interface {
	CreatePrescription(context.Context, *Prescription, *Response) error
	GetPrescriptions(context.Context, *GetRequest, *GetResponse) error
}

func RegisterPrescriptionServiceHandler(s server.Server, hdlr PrescriptionServiceHandler, opts ...server.HandlerOption) error {
	type prescriptionService interface {
		CreatePrescription(ctx context.Context, in *Prescription, out *Response) error
		GetPrescriptions(ctx context.Context, in *GetRequest, out *GetResponse) error
	}
	type PrescriptionService struct {
		prescriptionService
	}
	h := &prescriptionServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PrescriptionService{h}, opts...))
}

type prescriptionServiceHandler struct {
	PrescriptionServiceHandler
}

func (h *prescriptionServiceHandler) CreatePrescription(ctx context.Context, in *Prescription, out *Response) error {
	return h.PrescriptionServiceHandler.CreatePrescription(ctx, in, out)
}

func (h *prescriptionServiceHandler) GetPrescriptions(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.PrescriptionServiceHandler.GetPrescriptions(ctx, in, out)
}
